package rc.championship.decoder.explorer;

import javax.swing.ActionMap;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//rc.championship.decoder.explorer//DecoderExplorer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "DecoderExplorerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "rc.championship.decoder.explorer.DecoderExplorerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_DecoderExplorerAction",
        preferredID = "DecoderExplorerTopComponent"
)
@Messages({
    "CTL_DecoderExplorerAction=DecoderExplorer",
    "CTL_DecoderExplorerTopComponent=DecoderExplorer Window",
    "HINT_DecoderExplorerTopComponent=This is a DecoderExplorer window"
})
public final class DecoderExplorerTopComponent extends TopComponent implements ExplorerManager.Provider {

    private transient ExplorerManager explorerManager = new ExplorerManager();

    public DecoderExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_DecoderExplorerTopComponent());
        setToolTipText(Bundle.HINT_DecoderExplorerTopComponent());

        ActionMap actionMap = getActionMap();
        actionMap.put("delete", ExplorerUtils.actionDelete(explorerManager, true)); // NOI18N
        associateLookup(ExplorerUtils.createLookup(explorerManager, actionMap));
        DecoderFactory decoderFactory = new DecoderFactory();
        explorerManager.setRootContext(new DecoderRootNode(decoderFactory));
        explorerManager.getRootContext().setDisplayName("Decoders");

    }

    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decoderPane = new BeanTreeView();

        setLayout(new java.awt.BorderLayout());
        add(decoderPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane decoderPane;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        ExplorerUtils.activateActions(explorerManager, true);
    }

    @Override
    public void componentClosed() {
        ExplorerUtils.activateActions(explorerManager, false);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
